
/****************è¡¨ç»æ****************/

  CREATE TABLE "SCOTT"."T_COMPARE" 
   (	"CP_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"LEFT_DB_ID" VARCHAR2(32), 
	"RIGHT_DB_ID" VARCHAR2(32), 
	"CP_STATE" VARCHAR2(5), 
	"CRT_TM" DATE, 
	 CONSTRAINT "PK_COMPARE_ID" PRIMARY KEY ("CP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


/**************æ¬è¡¨æ³¨é**************/

		æ æ³¨é


/**************æ¬è¡¨ç´¢å¼**************/

INDEX_NAME(ç´¢å¼åç§°) INDEX_TYPE(ç´¢å¼ç±»å) UNIQUENESS(å¯ä¸æ§çº¦æ)COLUMNS(ç´¢å¼åå«çå­æ®µ)
PK_COMPARE_ID                NORMAL                       UNIQUE                        CP_ID                         
