
/****************è¡¨ç»æ****************/

  CREATE TABLE "SCOTT"."T_COMPARE_DETAIL" 
   (	"DT_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"CP_ID" VARCHAR2(32), 
	"LEFT_TAB_NM" VARCHAR2(100), 
	"LEFT_TAB_COLU" VARCHAR2(100), 
	"LEFT_TAB_TP" VARCHAR2(100), 
	"RIGHT_TAB_NM" VARCHAR2(100), 
	"RIGHT_TAB_COLU" VARCHAR2(100), 
	"RIGHT_TAB_TP" VARCHAR2(100), 
	"DT_STATE" VARCHAR2(5), 
	 CONSTRAINT "PK_COMPARE_DETAIL_ID" PRIMARY KEY ("DT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 


/**************æ¬è¡¨æ³¨é**************/

		æ æ³¨é


/**************æ¬è¡¨ç´¢å¼**************/

INDEX_NAME(ç´¢å¼åç§°) INDEX_TYPE(ç´¢å¼ç±»å) UNIQUENESS(å¯ä¸æ§çº¦æ)COLUMNS(ç´¢å¼åå«çå­æ®µ)
PK_COMPARE_DETAIL_ID         NORMAL                       UNIQUE                        DT_ID                         
